# Generated by Django 2.1.15 on 2021-12-29 09:53

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_time', models.DateTimeField(auto_now_add=True, verbose_name='下载时间')),
            ],
            options={
                'verbose_name': '下载历史',
                'verbose_name_plural': '下载历史',
                'db_table': 'download_history',
            },
        ),
        migrations.CreateModel(
            name='EmailVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_addr', models.EmailField(default='', max_length=254, verbose_name='邮箱地址')),
                ('verify_code', models.CharField(max_length=6, verbose_name='验证码')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证',
                'verbose_name_plural': '邮箱验证',
                'db_table': 'email_verify',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browse_time', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('ip_addr', models.CharField(max_length=25, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '浏览历史',
                'verbose_name_plural': '浏览历史',
                'db_table': 'browse_history',
            },
        ),
        migrations.CreateModel(
            name='SupportMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_amount', models.FloatField(default=0.0, verbose_name='支付金额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('order_id', models.CharField(max_length=100, verbose_name='订单号')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('pay_finish', models.BooleanField(default=False, verbose_name='是否完成交易')),
                ('ip_addr', models.CharField(max_length=25, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '支付历史',
                'verbose_name_plural': '支付历史',
                'db_table': 'support_me',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=30, verbose_name='工具名称')),
                ('tool_describe', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='介绍')),
                ('tool_file', models.FileField(upload_to='Files/', verbose_name='文件路径')),
                ('tool_icon', models.ImageField(upload_to='Icons/', verbose_name='图标路径')),
                ('tool_watch', models.IntegerField(default=0, verbose_name='浏览量')),
                ('tool_download', models.IntegerField(default=0, verbose_name='下载量')),
                ('tool_upload_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tool_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tool_is_checked', models.BooleanField(default=False, verbose_name='是否通过审核')),
            ],
            options={
                'verbose_name': '工具',
                'verbose_name_plural': '工具',
                'db_table': 'tool_info',
            },
        ),
        migrations.CreateModel(
            name='ToolComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('good', models.IntegerField(default=0, verbose_name='点赞量')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToolsBox.Tool', verbose_name='评论工具')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'tool_comment',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('user_age', models.IntegerField(verbose_name='年龄')),
                ('user_password', models.CharField(max_length=255, verbose_name='密码')),
                ('user_email', models.EmailField(default='', max_length=254, unique=True, verbose_name='邮箱')),
                ('user_reg_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user_info',
            },
        ),
        migrations.AddField(
            model_name='toolcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToolsBox.User', verbose_name='评论用户'),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_upload_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToolsBox.User', verbose_name='上传用户'),
        ),
        migrations.AddField(
            model_name='supportme',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolsBox.User', verbose_name='打赏用户'),
        ),
        migrations.AddField(
            model_name='history',
            name='browse_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToolsBox.Tool', verbose_name='浏览内容'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolsBox.User', verbose_name='浏览用户'),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='download_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToolsBox.Tool', verbose_name='下载内容'),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToolsBox.User', verbose_name='下载用户'),
        ),
    ]
