# Generated by Django 2.2 on 2022-06-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolsBox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_age',
        ),
        migrations.AddField(
            model_name='user',
            name='user_real_name',
            field=models.CharField(default='', max_length=10, verbose_name='真实姓名'),
        ),
    ]
