"""
Django settings for MyTools project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
# import pymysql
# pymysql.install_as_MySQLdb()
import MySQLdb

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vq$-i=_cxndj7ukk85h@8yj$n!am&k*zg^4xa44c8&v-$0-kk5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False # True 

ALLOWED_HOSTS = ['*', ]

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ToolsBox',
    'Resume',
    'Online',
    'ckeditor',
    'ckeditor_uploader',
]

MEDIA_URL = '/upload_files/'  # 你的media url 在Url显示并没什么关系
# MEDIA_ROOT = os.path.join(BASE_DIR, 'static/upload_files/')
MEDIA_ROOT = "/home/pi/Code/Django_proj/MyTools/upload_files/"  # 修改为自己的路径

# ckeditor配置
CKEDITOR_JQUERY_URL = 'https://cdn.bootcdn.net/ajax/libs/jquery/2.1.4/jquery.min.js'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',  # 工具栏全部功能
        'extraPlugins': 'codesnippet',
        'height': 300,  # 高度
        'width': 730,  # 宽度
    },
}
CKEDITOR_UPLOAD_PATH = "upload_files/"  # 他的目录相对与media root 就是 media root + CKEDITOR_UPLOAD_PATH 不能写成"/uploads/"
CKEDITOR_IMAGE_BACKEND = 'pillow'

# 设置跨域可用
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = ("https://guohtgo.asuscomm.com:*","https://192.168.1.1:*",)
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)

CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ToolsBox.middleware.IpBan',
]

ROOT_URLCONF = 'MyTools.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyTools.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.mysql', #设置为mysql数据库
        'NAME': 'ToolsBoxPi',  #mysql数据库名
        'USER': 'root',  #mysql用户名
        'PASSWORD': 'GuoHT990520#2',   #mysql密码
        'HOST': '',  #留空默认为localhost
        'PORT': '',  #留空默认为3306端口
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://:guoht990520_2_redis@127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_REDIS_ALIAS = "default"


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

# debug=False 设置静态文件的保存目录
STATIC_URL = '/static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]  # debug=True生效
STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # debug=False生效


# 邮件配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = '2651156641@qq.com'
EMAIL_HOST_PASSWORD = 'zmbxcfcbtdyweaif'
EMAIL_USE_TLS = True  # 这里必须是 True，否则发送不成功

# 获取csrf_token时需要的参数{"get_csrf_password":"i am guohtgo"}
get_csrf_password = 'i am guohtgo'

ALIPAY_APP_ID = "2021000117676739"
ALIPAY_RETURN_URL = "http://guohtgo.asuscomm.com:8001/tools/index"
ALIPAY_NOTIFY_URL = "http://guohtgo.asuscomm.com:8001/tools/notify"
# superuser:
# 用户名:  16227
# 电子邮件地址:  1622761893@qq.com
# Password:  guoht990520

AES_KEY = "guohtguoht990520"

DOCS_URL = '/doc/'  # url
DOCS_ROOT = BASE_DIR +'/doc/build/html'   # 文档路径