# Generated by Django 2.1.15 on 2021-12-29 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ToolsBox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('file_name', models.TextField(max_length=20, verbose_name='文件名')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
                ('user_belong', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ToolsBox.User', verbose_name='所属用户')),
            ],
        ),
    ]
