# Generated by Django 2.1.15 on 2021-12-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_userresume_watch_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userresume',
            options={'verbose_name': '用户简历', 'verbose_name_plural': '用户简历'},
        ),
        migrations.AlterModelTable(
            name='userresume',
            table='user_resume',
        ),
    ]
