# Generated by Django 2.1.15 on 2021-12-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_userresume_first_page_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='first_page_img',
            field=models.ImageField(blank=True, null=True, upload_to='Icons/', verbose_name='简历封面'),
        ),
    ]
