# Generated by Django 2.2 on 2022-06-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0005_auto_20211230_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='first_page_img',
            field=models.ImageField(blank=True, null=True, upload_to='Resume/', verbose_name='简历封面'),
        ),
    ]
